import { Serie } from './serie.js';

export const data = [
  new Serie(1,"Breaking Bad","AMC", 5, "https://th.bing.com/th/id/OIP.DG6l6rHB_gi8gg8DdjeCpwHaEK?rs=1&pid=ImgDetMain", "Breaking Bad es una serie de televisión estadounidense creada por Vince Gilligan. La trama sigue la transformación de Walter White, un profesor de química de secundaria con cáncer de pulmón, quien se convierte en un fabricante y traficante de metanfetamina para asegurar el futuro financiero de su familia. Con su exalumno, Jesse Pinkman, forman una asociación complicada en el mundo del crimen, enfrentándose a rivales, dilemas éticos y consecuencias devastadoras. La serie es aclamada por su guion inteligente, personajes complejos y actuaciones sobresalientes, especialmente la de Bryan Cranston como Walter White.", "https://www.amctv.la/"),
  new Serie(2,"Orange Is the New Black", "Netflix", 6, "https://www.cleveland.com/resizer/VawaBraTke1sojjx62LXGI148NE=/1280x0/smart/advancelocal-adapter-image-uploads.s3.amazonaws.com/image.cleveland.com/home/cleve-media/width2048/img/ent_impact_home/photo/oitnb-b41dfd96f03e9ed3.jpg", "Orange Is the New Black es una serie de televisión estadounidense creada por Jenji Kohan. La historia se basa en las memorias de Piper Kerman y sigue la vida de Piper Chapman, una mujer de clase media que es sentenciada a prisión por su participación en el transporte de dinero de drogas para su exnovia años atrás. La serie explora la vida en una prisión federal de mujeres y presenta una amplia gama de personajes, cada uno con su propia historia y luchas. A lo largo de las temporadas, la serie aborda temas como la raza, la sexualidad, la política carcelaria y la humanidad en condiciones extremas.", "https://www.netflix.com/login"),
  new Serie(3, "Game of Thrones","HBO", 7, "https://th.bing.com/th/id/R.3a0d20e4aeea759e11e3b1ae15a13d2e?rik=ayNtiNLMC%2bwNJw&riu=http%3a%2f%2fassets1.ignimgs.com%2f2017%2f06%2f28%2ftop100-gotcharacters-desktop-1498688689918.jpg&ehk=nr0S%2bGBFkIQSYnem7rRzNfpDzfeWGD2%2f7a69QHbWRVQ%3d&risl=&pid=ImgRaw&r=0", "Game of Thrones es una serie de televisión estadounidense basada en la serie de novelas Canción de hielo y fuego escrita por George R.R. Martin. Creada por David Benioff y D.B. Weiss, la serie se desarrolla en el continente ficticio de Westeros y sigue las luchas políticas y militares entre las poderosas casas nobles por el control del Trono de Hierro y del reino de los Siete Reinos. Con una trama compleja, personajes memorables y giros inesperados, la serie se ha convertido en un fenómeno cultural global y una de las más populares y exitosas de la televisión.", "https://www.max.com/co/es"),
  new Serie(4, "The Big Bang Theory", "CBS", 12, "https://th.bing.com/th/id/R.6a3d782e2615b5ded0eaffd23abea0a7?rik=tvBpbawNnUfohw&pid=ImgRaw&r=0", "The Big Bang Theory sigue las vidas de un grupo de amigos, destacando a Leonard y Sheldon, dos físicos altamente inteligentes pero socialmente ineptos, junto con su vecina Penny, una aspirante a actriz. La serie explora sus interacciones en el apartamento compartido, así como en sus trabajos en el Instituto de Tecnología de California. A lo largo de sus doce temporadas, la serie se ganó el reconocimiento por su humor inteligente, sus referencias a la cultura geek y científica, y la evolución de los personajes a lo largo del tiempo. Con su final en 2019, se estableció como una de las comedias de situación más populares y duraderas en la televisión estadounidense.", "https://www.cbs.com/shows/"),
  new Serie(5, "Sherlock", "BBC",  4, "https://media.senscritique.com/media/000009574538/1200/sherlock.jpg", "Sherlock es una serie de televisión británica creada por Steven Moffat y Mark Gatiss, basada en las historias del famoso detective Sherlock Holmes de Sir Arthur Conan Doyle. La serie moderniza las aventuras del detective en el Londres contemporáneo, donde Sherlock, interpretado por Benedict Cumberbatch, utiliza su brillantez deductiva para resolver casos junto a su fiel amigo, el Dr. John Watson, interpretado por Martin Freeman. La serie es elogiada por su ingenioso guion, actuaciones destacadas y su estilo visual distintivo. A lo largo de sus cuatro temporadas, Sherlock se convirtió en un éxito internacional y desarrolló una base de seguidores apasionados.", "https://www.bbc.co.uk/iplayer/categories/drama-and-soaps/featured"),
  new Serie(6, "A Very English Scandal", "BBC", 2, "https://th.bing.com/th/id/R.6c053e6e7a33ddb623aea9384fd42b0a?rik=22%2b5APd66%2f4v6w&pid=ImgRaw&r=0", "A Very English Scandal es una miniserie británica que relata el escándalo político en torno al político Jeremy Thorpe en la década de 1970. Hugh Grant interpreta a Thorpe y Ben Whishaw a Norman Scott, su ex amante. La serie sigue la conspiración de Thorpe para silenciar a Scott y los eventos que llevan a su juicio por intento de asesinato. Elogiada por las actuaciones y el guion, explora temas como el poder y la corrupción en la sociedad británica.", "https://www.bbc.co.uk/iplayer/categories/drama-and-soaps/featured")
] 
  